"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {X,Search,MapPin,Plane,Calculator,Settings2,Route,Compass} from 'lucide-react';
import type {Globe,TerrainPoint,ViewInfo} from '@/lib/globe';
import type {TrafficTarget} from '@/lib/traffic';
import type {useTraffic} from '@/hooks/use-traffic';
import {CALCULATORS,calculate,type Calculator as Calc} from '@/lib/calculators';
import {FEATURES,type ToolTab} from '@/lib/features';
import {distanceKm,dms,wrap,parseCoordinates,routeDistance,polygonArea,download,geoJSON,type GeoPoint} from '@/lib/geo';
import {saveStored,readStored} from '@/lib/session';
import {EMPTY_WORKSPACE,parseWorkspace,importGeoJSON,csv,gpx,type Workspace} from '@/lib/workspace';

function CalculatorForm({tool,view}:{tool:Calc;view:ViewInfo}){
 const [values,setValues]=useState<Record<string,number>>(()=>Object.fromEntries(tool.fields.map(f=>[f.key,f.value])));
 const [result,setResult]=useState<Record<string,number|string>|null>(null),[error,setError]=useState('');
 return <section><h3>{tool.name}</h3><p className="tool-note">{tool.note}</p><form onSubmit={event=>{event.preventDefault();try{setResult(calculate(tool,values));setError('');}catch(e){setError((e as Error).message);setResult(null);}}}><div className="tool-fields">{tool.fields.map(f=><label key={f.key}>{f.label}<input type="number" step="any" required min={f.min} max={f.max} value={Number.isNaN(values[f.key])?'':values[f.key]} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value===''?NaN:Number(e.target.value)}))}/></label>)}</div><div className="tool-actions"><button type="submit">Calculate</button>{tool.fields.some(f=>f.key==='lat')&&<button type="button" onClick={()=>setValues(v=>({...v,lat:view.latitude,...('lon' in v?{lon:view.longitude}:{})}))}>Use map center</button>}</div></form>{error&&<p role="alert" className="tool-error">{error}</p>}{result&&<dl className="tool-results">{Object.entries(result).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{typeof value==='number'?value.toLocaleString(undefined,{maximumFractionDigits:6}):value}</dd></div>)}</dl>}</section>;
}

export default function ToolsDrawer({open,onClose,getGlobe,ready,view,point,feeds,selected,onSelect,paused,onPaused}:{open:boolean;onClose:()=>void;getGlobe:()=>Globe|null;ready:boolean;view:ViewInfo;point:TerrainPoint|null;feeds:ReturnType<typeof useTraffic>;selected:TrafficTarget|null;onSelect:(t:TrafficTarget)=>void;paused:boolean;onPaused:(p:boolean)=>void}){
 const [tab,setTab]=useState<ToolTab>('Explore'),[query,setQuery]=useState(''),[message,setMessage]=useState('');
 const [workspace,setWorkspace]=useState<Workspace>(()=>{try{return parseWorkspace(readStored('atlas-workspace-v1',EMPTY_WORKSPACE));}catch{return EMPTY_WORKSPACE;}});
 const [countryQuery,setCountryQuery]=useState(''),[countries,setCountries]=useState<{name:string;lat:number;lng:number}[]>([]);
 const [coordinateInput,setCoordinateInput]=useState(''),[placeName,setPlaceName]=useState(''),[calcId,setCalcId]=useState('calc-1');
 const [polygon,setPolygon]=useState(false),[ring,setRing]=useState(0),[grid,setGrid]=useState(false),[speed,setSpeed]=useState(80),[stop,setStop]=useState(10);
 const [profile,setProfile]=useState<{km:number;height:number|null}[]>([]),[sampling,setSampling]=useState(false);
 const [quality,setQuality]=useState<'eco'|'balanced'|'detail'>('eco');
 const [appearance,setAppearance]=useState({lighting:false,brightness:1,contrast:1,atmosphere:true,fog:true,stars:true});
 const [filter,setFilter]=useState(''),[kind,setKind]=useState('all'),[minAlt,setMinAlt]=useState(''),[maxAlt,setMaxAlt]=useState(''),[minSpeed,setMinSpeed]=useState(''),[radius,setRadius]=useState(''),[maxAge,setMaxAge]=useState(''),[sort,setSort]=useState('distance'),[onlyWatch,setOnlyWatch]=useState(false);
 const [compare,setCompare]=useState<TrafficTarget[]>([]),[follow,setFollow]=useState(false),[trail,setTrail]=useState(false),[alertKm,setAlertKm]=useState(0);
 const [now,setNow]=useState(0),[page,setPage]=useState(0);
 const selectedId=selected?.id;
 const trails=useRef<{id:string;points:GeoPoint[]}>({id:'',points:[]});
 useEffect(()=>{if(!saveStored('atlas-workspace-v1',workspace)){const timer=setTimeout(()=>setMessage('Browser storage is full or unavailable. Export a backup to keep your work.'),0);return()=>clearTimeout(timer);}},[workspace]);
 useEffect(()=>{if(!open)return;const timer=setInterval(()=>setNow(Date.now()),2000);return()=>clearInterval(timer);},[open]);
 useEffect(()=>{if(!open||countries.length)return;let active=true;fetch('/data/countries.json').then(r=>r.json()).then(data=>{if(active)setCountries(data as typeof countries);}).catch(()=>{if(active)setMessage('Country index unavailable.');});return()=>{active=false;};},[open,countries.length]);
 useEffect(()=>{if(ready)getGlobe()?.setWorkspace(workspace.points,polygon,ring,grid);},[ready,getGlobe,workspace.points,polygon,ring,grid]);
 useEffect(()=>{if(ready)getGlobe()?.appearance(appearance);},[getGlobe,ready,appearance]);
 useEffect(()=>{if(ready)getGlobe()?.followTraffic(follow&&selectedId?selectedId:null);},[getGlobe,ready,follow,selectedId]);
 useEffect(()=>{if(!selected){getGlobe()?.showTrail([]);return;}if(trails.current.id!==selected.id)trails.current={id:selected.id,points:[]};const last=trails.current.points.at(-1);if(!last||last.latitude!==selected.latitude||last.longitude!==selected.longitude)trails.current.points=[...trails.current.points,{latitude:selected.latitude,longitude:selected.longitude}].slice(-60);getGlobe()?.showTrail(trail?trails.current.points:[]);},[selected,getGlobe,trail]);
 const navigate=useCallback((p:GeoPoint)=>{getGlobe()?.overview(p.longitude,p.latitude,500000);setWorkspace(w=>({...w,history:[p,...w.history.filter(h=>h.latitude!==p.latitude||h.longitude!==p.longitude)].slice(0,50)}));onClose();},[getGlobe,onClose]);
 const center:GeoPoint={latitude:view.latitude,longitude:view.longitude,name:placeName.trim()||undefined};
 const addPoint=(p:GeoPoint)=>{if(workspace.points.length>=200){setMessage('Maximum 200 waypoints.');return;}setProfile([]);setWorkspace(w=>({...w,points:[...w.points,{...p,name:p.name?.slice(0,120)}]}));};
 const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);setMessage('Copied to clipboard.');}catch{setMessage('Clipboard access unavailable.');}};
 const allTargets=useMemo(()=>[...feeds.air.targets,...feeds.maritime.targets],[feeds.air.targets,feeds.maritime.targets]);
 const targets=useMemo(()=>allTargets.filter(t=>(kind==='all'||t.kind===kind)&&(!filter||`${t.name} ${t.id} ${t.registration||''} ${t.aircraftType||''}`.toLowerCase().includes(filter.toLowerCase()))&&(!onlyWatch||workspace.watch.includes(t.id))&&(minAlt===''||t.altitude!==null&&t.altitude>=Number(minAlt))&&(maxAlt===''||t.altitude!==null&&t.altitude<=Number(maxAlt))&&(minSpeed===''||t.speed!==null&&t.speed>=Number(minSpeed))&&(radius===''||distanceKm(view.latitude,view.longitude,t.latitude,t.longitude)<=Number(radius))&&(maxAge===''||now-t.observedAt<=Number(maxAge)*1000)).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='altitude'?(b.altitude??-1)-(a.altitude??-1):sort==='speed'?(b.speed??-1)-(a.speed??-1):sort==='recent'?b.observedAt-a.observedAt:distanceKm(view.latitude,view.longitude,a.latitude,a.longitude)-distanceKm(view.latitude,view.longitude,b.latitude,b.longitude)),[allTargets,kind,filter,onlyWatch,workspace.watch,minAlt,maxAlt,minSpeed,radius,maxAge,now,sort,view.latitude,view.longitude]);
 const alerts=alertKm?allTargets.filter(t=>distanceKm(view.latitude,view.longitude,t.latitude,t.longitude)<=alertKm):[];
 const watch=(id:string)=>setWorkspace(w=>({...w,watch:w.watch.includes(id)?w.watch.filter(v=>v!==id):[...w.watch,id].slice(-200)}));
 const loadFile=async(file:File|undefined,backup=false)=>{if(!file)return;try{if(file.size>2e6)throw new Error('Use a file smaller than 2 MB.');const data=JSON.parse(await file.text());if(backup)setWorkspace(parseWorkspace(data));else{setProfile([]);setWorkspace(w=>({...w,points:importGeoJSON(data)}));}setMessage('Import complete.');}catch(e){setMessage((e as Error).message);}};
 const total=routeDistance(workspace.points),area=polygonArea(workspace.points);
 const exportTraffic=()=>download('atlas-traffic.csv',csv([['ID','Name','Kind','Latitude','Longitude','Altitude m','Speed knots','Reported UTC','Source'],...targets.map(t=>[t.id,t.name,t.kind,t.latitude,t.longitude,t.altitude,t.speed,new Date(t.observedAt).toISOString(),t.source])]),'text/csv');
 const validHeights=profile.flatMap(p=>p.height===null?[]:[p.height]),low=validHeights.length?Math.min(...validHeights):0,high=validHeights.length?Math.max(...validHeights):0;
 const profilePath=profile.map((p,i)=>p.height===null?'':`${i===0||profile[i-1].height===null?'M':'L'} ${20+p.km/Math.max(0.001,total)*580} ${175-(p.height-low)/Math.max(1,high-low)*140}`).join(' ');
 let ascent=0,descent=0;profile.slice(1).forEach((p,i)=>{if(p.height===null||profile[i].height===null)return;const delta=p.height-profile[i].height!;if(delta>0)ascent+=delta;else descent-=delta;});
 const matches=query.trim()?FEATURES.filter(f=>f.name.toLowerCase().includes(query.toLowerCase())):[];
 const selectedTool=CALCULATORS.find(c=>c.id===calcId)!;
 return <aside className="utility-drawer glass" hidden={!open} aria-label="Atlas utility workspace"><div className="utility-heading"><div><h2>Atlas workspace</h2><p>40 workflows · 60 calculators</p></div><button onClick={onClose} aria-label="Close tools"><X size={22}/></button></div>
 <div className="utility-search"><Search size={16}/><input aria-label="Search all 100 tools" placeholder="Search all 100 tools…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 {query&&<div className="tool-search-results">{matches.map(f=><button key={f.id} onClick={()=>{setTab(f.tab);if(f.id.startsWith('calc'))setCalcId(f.id);setQuery('');setMessage(`${f.name} · ${f.tab}`);}}>{f.name}<small>{f.tab}</small></button>)}{!matches.length&&<p>No matching tools.</p>}</div>}
 <nav className="utility-tabs" aria-label="Tool categories">{(['Explore','Routes','Traffic','Display','Calculators'] as ToolTab[]).map((t,i)=>{const Icon=[Compass,Route,Plane,Settings2,Calculator][i];return <button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}><Icon size={16}/>{t}</button>;})}</nav>
 {message&&<p className="tool-message" role="status">{message}<button onClick={()=>setMessage('')} aria-label="Dismiss message">×</button></p>}
 <div className="utility-body">
 {tab==='Explore'&&<>
 <section><h3>Find a country</h3><input aria-label="Country name" placeholder="Country name" value={countryQuery} onChange={e=>setCountryQuery(e.target.value)}/><div className="country-results">{countryQuery&&countries.filter(c=>c.name.toLowerCase().includes(countryQuery.toLowerCase())).slice(0,12).map(c=><button key={c.name} onClick={()=>navigate({latitude:c.lat,longitude:c.lng,name:c.name})}>{c.name}<MapPin size={14}/></button>)}</div></section>
 <section><h3>Navigate precisely</h3><p className="tool-note">Decimal degrees or DMS: 40° 30′ 0″ N, 74° 0′ 0″ W</p><form onSubmit={e=>{e.preventDefault();try{navigate(parseCoordinates(coordinateInput));}catch(error){setMessage((error as Error).message);}}}><input aria-label="Decimal or DMS coordinates" value={coordinateInput} placeholder="Latitude, longitude" onChange={e=>setCoordinateInput(e.target.value)}/><div className="tool-actions"><button type="submit" disabled={!ready}>Navigate</button><button type="button" onClick={()=>{if(!navigator.geolocation){setMessage('Device location is unavailable.');return;}navigator.geolocation.getCurrentPosition(p=>navigate({latitude:p.coords.latitude,longitude:p.coords.longitude,name:'My location'}),()=>setMessage('Location unavailable or permission denied.'),{timeout:10000,maximumAge:60000});}}>My location</button><button type="button" disabled={!ready} onClick={()=>navigate({latitude:-view.latitude,longitude:wrap(view.longitude+180),name:'Antipode'})}>Antipode</button></div></form><p className="tool-note">{dms(view.latitude)} · {dms(view.longitude,false)}</p><div className="tool-actions"><button onClick={()=>void copy(`${view.latitude.toFixed(6)}, ${view.longitude.toFixed(6)}`)}>Copy center</button><button onClick={()=>{const camera=getGlobe()?.cameraSnapshot();if(camera)void copy(`${location.origin}${location.pathname}#view=${encodeURIComponent(JSON.stringify(camera))}`);else setMessage('Start the globe first.');}}>Copy exact view link</button></div></section>
 <section><h3>Saved views & notes</h3><input aria-label="Place or annotation name" maxLength={120} placeholder="Name this view or map note" value={placeName} onChange={e=>setPlaceName(e.target.value)}/><div className="tool-actions"><button disabled={!ready} onClick={()=>{const camera=getGlobe()?.cameraSnapshot();if(!camera)return;setWorkspace(w=>({...w,views:[...w.views,{id:crypto.randomUUID(),name:placeName.trim()||`View ${w.views.length+1}`,camera}].slice(-100)}));}}>Save view</button><button onClick={()=>addPoint(center)}>Annotate center</button></div><div className="saved-list">{workspace.views.map(v=><div key={v.id}><button onClick={()=>{getGlobe()?.restoreCamera(v.camera);onClose();}}>{v.name}</button><button aria-label={`Delete ${v.name}`} onClick={()=>setWorkspace(w=>({...w,views:w.views.filter(p=>p.id!==v.id)}))}>×</button></div>)}</div></section>
 <section><h3>Visit history</h3><div className="saved-list">{workspace.history.length?workspace.history.slice(0,15).map((p,i)=><button key={i} onClick={()=>navigate(p)}>{p.name||`${p.latitude.toFixed(3)}, ${p.longitude.toFixed(3)}`}</button>):<p className="tool-note">Places opened from these tools appear here.</p>}</div></section>
 <section><h3>Backup & restore</h3><p className="tool-note">Views, waypoints, annotations, history and watchlist are stored on this browser. Export a backup to move them to another device.</p><div className="tool-actions"><button onClick={()=>download('atlas-workspace.json',JSON.stringify(workspace,null,2))}>Export backup</button><label className="file-button">Restore backup<input type="file" accept="application/json,.json" onChange={e=>void loadFile(e.target.files?.[0],true)}/></label></div></section>
 </>}
 {tab==='Routes'&&<>
 <section><h3>Route & area planner</h3><p className="tool-note">Add the map center or a selected terrain point. Distances follow a spherical Earth; polygons use the shorter enclosed area. Up to 200 points.</p><div className="tool-actions"><button onClick={()=>addPoint(center)}>Add map center</button><button disabled={!point} onClick={()=>{if(point)addPoint({latitude:point.latitude,longitude:point.longitude,name:placeName||undefined});}}>Add selected point</button><button disabled={!workspace.points.length} onClick={()=>{setProfile([]);setWorkspace(w=>({...w,points:w.points.slice(0,-1)}));}}>Undo point</button></div><div className="tool-fields"><label>Waypoint coordinates<input value={coordinateInput} placeholder="Latitude, longitude" onChange={e=>setCoordinateInput(e.target.value)}/></label><label>Annotation<input maxLength={120} value={placeName} onChange={e=>setPlaceName(e.target.value)}/></label></div><button onClick={()=>{try{addPoint({...parseCoordinates(coordinateInput),name:placeName||undefined});}catch(e){setMessage((e as Error).message);}}}>Add coordinates</button>
 <ol className="waypoint-list">{workspace.points.map((p,i)=><li key={i}><button onClick={()=>navigate(p)}>{p.name||`Point ${i+1}`} · {p.latitude.toFixed(3)}, {p.longitude.toFixed(3)}</button></li>)}</ol>
 <div className="tool-actions"><button disabled={workspace.points.length<2} onClick={()=>{setProfile([]);setWorkspace(w=>({...w,points:[...w.points].reverse()}));}}>Reverse route</button><button disabled={!ready||!workspace.points.length} onClick={()=>{getGlobe()?.fitPoints(workspace.points);onClose();}}>Fit route</button><button disabled={!workspace.points.length} onClick={()=>{setProfile([]);setWorkspace(w=>({...w,points:[]}));}}>Clear route</button></div>
 <label className="tool-check"><input type="checkbox" checked={polygon} onChange={e=>setPolygon(e.target.checked)}/>Fill polygon & measure area</label><dl className="tool-results"><div><dt>Route distance</dt><dd>{total.toFixed(2)} km · {(total/1.852).toFixed(2)} nm</dd></div>{polygon&&<div><dt>Polygon area</dt><dd>{area.toFixed(3)} km²</dd></div>}</dl>
 <label>Range rings from first waypoint (km; 0 disables)<input type="number" min={0} max={2000} value={ring} onChange={e=>setRing(Math.max(0,Math.min(2000,Number(e.target.value))))}/></label><p className="tool-note">Three rings at 1×, 2× and 3× your chosen radius.</p></section>
 <section><h3>Multi-stop timing</h3><div className="tool-fields"><label>Travel speed km/h<input type="number" min={0.1} value={speed} onChange={e=>setSpeed(Math.max(0.1,Number(e.target.value)))}/></label><label>Minutes per intermediate stop<input type="number" min={0} value={stop} onChange={e=>setStop(Math.max(0,Number(e.target.value)))}/></label></div><p>{(total/speed*60+Math.max(0,workspace.points.length-2)*stop).toFixed(1)} minutes including stops</p></section>
 <section><h3>Terrain profile</h3><button disabled={!ready||sampling||workspace.points.length<2} onClick={async()=>{setSampling(true);try{const data=await getGlobe()?.profile(workspace.points);if(data)setProfile(data);}catch(e){setMessage((e as Error).message);}finally{setSampling(false);}}}>{sampling?'Sampling terrain…':'Sample route elevations'}</button><p className="tool-note">129 samples at terrain level 12. Narrow peaks and valleys can be missed; gaps mean unavailable data.</p>{profile.length>0&&<><svg role="img" aria-label="Elevation along route" viewBox="0 0 640 200"><path d={profilePath} fill="none" stroke="#a4ecdb" strokeWidth="2"/><text x="20" y="15" fill="#b9cedc">{high.toFixed(0)} m</text><text x="20" y="195" fill="#b9cedc">{low.toFixed(0)} m · {total.toFixed(1)} km</text></svg><p>Sampled ascent {ascent.toFixed(0)} m · descent {descent.toFixed(0)} m</p></>}</section>
 <section><h3>Import & export</h3><div className="tool-actions"><label className="file-button">Import GeoJSON<input type="file" accept=".json,.geojson" onChange={e=>void loadFile(e.target.files?.[0])}/></label><button onClick={()=>download('atlas-route.gpx',gpx(workspace.points),'application/gpx+xml')}>Export GPX</button><button onClick={()=>download('atlas-points.geojson',geoJSON(workspace.points),'application/geo+json')}>Export GeoJSON</button><button onClick={()=>download('atlas-waypoints.csv',csv([['Name','Latitude','Longitude'],...workspace.points.map(p=>[p.name||'',p.latitude,p.longitude])]),'text/csv')}>Export CSV</button></div></section>
 </>}
 {tab==='Traffic'&&<>
 <section><h3>Traffic operations</h3><p className="tool-note">Enable traffic layers in View & layers. This list works even when the 3D renderer is unavailable.</p><div className="tool-actions"><button onClick={()=>{feeds.air.refresh();feeds.maritime.refresh();setMessage('Refreshing enabled feeds.');}}>Refresh now</button><button aria-pressed={paused} onClick={()=>onPaused(!paused)}>{paused?'Resume polling':'Pause polling'}</button><button onClick={exportTraffic}>Export filtered CSV</button></div>
 <input aria-label="Search traffic callsign or ID" placeholder="Search callsign, registration, type or ID" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}/>
 <div className="tool-fields"><label>Kind<select value={kind} onChange={e=>{setKind(e.target.value);setPage(0);}}><option value="all">All reports</option><option value="air">Civil / unclassified aircraft</option><option value="military">Military aircraft</option><option value="maritime">Vessels</option></select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}>{['distance','name','altitude','speed','recent'].map(v=><option key={v}>{v}</option>)}</select></label><label>Minimum altitude m<input type="number" value={minAlt} onChange={e=>setMinAlt(e.target.value)}/></label><label>Maximum altitude m<input type="number" value={maxAlt} onChange={e=>setMaxAlt(e.target.value)}/></label><label>Minimum speed knots<input type="number" min={0} value={minSpeed} onChange={e=>setMinSpeed(e.target.value)}/></label><label>Within km of map center<input type="number" min={0} value={radius} onChange={e=>setRadius(e.target.value)}/></label><label>Maximum report age seconds<input type="number" min={0} value={maxAge} onChange={e=>setMaxAge(e.target.value)}/></label></div>
 <label className="tool-check"><input type="checkbox" checked={onlyWatch} onChange={e=>setOnlyWatch(e.target.checked)}/>Watchlist only ({workspace.watch.length} saved IDs)</label><p>{targets.length} matching reports</p>
 <div className="traffic-roster">{targets.slice(Math.min(page,Math.max(0,Math.ceil(targets.length/30)-1))*30,Math.min(page,Math.max(0,Math.ceil(targets.length/30)-1))*30+30).map(t=><div key={t.id} className={selected?.id===t.id?'selected':''}><button onClick={()=>onSelect(t)}><strong>{t.name}</strong><span>{t.aircraftType||t.kind} · {distanceKm(view.latitude,view.longitude,t.latitude,t.longitude).toFixed(0)} km · {Math.max(0,Math.round((now-t.observedAt)/1000))}s ago</span></button><button aria-label={`Watch ${t.name}`} aria-pressed={workspace.watch.includes(t.id)} onClick={()=>watch(t.id)}>{workspace.watch.includes(t.id)?'★':'☆'}</button><button aria-label={`Compare ${t.name}`} onClick={()=>setCompare(c=>[...c.filter(p=>p.id!==t.id),t].slice(-2))}>⇄</button></div>)}</div><div className="tool-actions"><button disabled={page===0} onClick={()=>setPage(n=>Math.max(0,n-1))}>Previous</button><button disabled={(page+1)*30>=targets.length} onClick={()=>setPage(n=>n+1)}>Next 30</button></div>
 </section>
 {selected&&<section><h3>{selected.name}</h3><dl className="tool-results"><div><dt>Identifier</dt><dd>{selected.id}</dd></div><div><dt>Registration / type</dt><dd>{selected.registration||'Unknown'} · {selected.aircraftType||'Unknown'}</dd></div><div><dt>Position</dt><dd>{selected.latitude.toFixed(5)}, {selected.longitude.toFixed(5)}</dd></div><div><dt>Altitude / reference</dt><dd>{selected.altitude===null?'Unknown':`${Math.round(selected.altitude)} m`} · {selected.altitudeReference}</dd></div><div><dt>Speed / track</dt><dd>{selected.speed??'Unknown'} kn · {selected.heading??'Unknown'}°</dd></div><div><dt>Squawk / vertical rate</dt><dd>{selected.squawk||'Not reported'} · {selected.verticalRate??'Unknown'} ft/min</dd></div><div><dt>Last report</dt><dd>{new Date(selected.observedAt).toLocaleString()} · {selected.source}</dd></div></dl><div className="tool-actions"><button onClick={()=>navigate(selected)}>Center on report</button><button onClick={()=>watch(selected.id)}>{workspace.watch.includes(selected.id)?'Unwatch':'Watch'}</button></div><label className="tool-check"><input type="checkbox" checked={follow} onChange={e=>setFollow(e.target.checked)}/>Follow selected target (latest received position)</label><label className="tool-check"><input type="checkbox" checked={trail} onChange={e=>setTrail(e.target.checked)}/>Show observed ground trail (this session)</label></section>}
 {compare.length>0&&<section><h3>Compare reports</h3><div className="comparison">{compare.map(t=><article key={t.id}><strong>{t.name}</strong><p>{t.kind}<br/>{t.altitude??'Unknown'} m<br/>{t.speed??'Unknown'} knots<br/>{t.heading??'Unknown'}° track</p></article>)}</div>{compare.length===2&&<p>Reported separation {distanceKm(compare[0].latitude,compare[0].longitude,compare[1].latitude,compare[1].longitude).toFixed(2)} km. Report times may differ.</p>}<button onClick={()=>setCompare([])}>Clear comparison</button></section>}
 <section><h3>Local proximity alert</h3><label>Alert radius from view center km (0 disables)<input type="number" min={0} max={500} value={alertKm} onChange={e=>setAlertKm(Math.max(0,Math.min(500,Number(e.target.value))))}/></label>{alertKm>0&&<p role="status">{alerts.length?`${alerts.length} reports inside ${alertKm} km: ${alerts.slice(0,3).map(t=>t.name).join(', ')}`:'No received reports within this radius.'}</p>}<p className="tool-note">In-app only while enabled. Incomplete public coverage; not a safety or collision alert.</p></section>
 <section><h3>Traffic statistics</h3><dl className="tool-results">{(['air','military','maritime'] as const).map(k=><div key={k}><dt>{k}</dt><dd>{allTargets.filter(t=>t.kind===k).length}</dd></div>)}<div><dt>Highest reported aircraft</dt><dd>{allTargets.filter(t=>t.kind!=='maritime'&&t.altitude!==null).sort((a,b)=>(b.altitude||0)-(a.altitude||0))[0]?.name||'No reports'}</dd></div><div><dt>Fastest report</dt><dd>{[...allTargets].sort((a,b)=>(b.speed||0)-(a.speed||0))[0]?.name||'No reports'}</dd></div></dl></section>
 </>}
 {tab==='Display'&&<><section><h3>Performance & display</h3><p className="tool-note">Eco reduces pixels and tile memory. Terrain height data stays unchanged; mesh detail adjusts to available resources.</p><label>Graphics quality<select value={quality} onChange={e=>{const q=e.target.value as typeof quality;setQuality(q);getGlobe()?.setQuality(q);}}><option value="eco">Eco · recommended on phones</option><option value="balanced">Balanced</option><option value="detail">High detail</option></select></label><div className="tool-actions"><button onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setMessage('Fullscreen is not supported in this browser.');}}}>Toggle fullscreen</button></div><label className="tool-check"><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/>Geographic graticule (10°)</label></section><section><h3>Light & atmosphere</h3>{(['lighting','atmosphere','fog','stars'] as const).map(k=><label className="tool-check" key={k}><input type="checkbox" checked={appearance[k]} onChange={e=>setAppearance(a=>({...a,[k]:e.target.checked}))}/>{({lighting:'Day / night illumination at current UTC',atmosphere:'Atmosphere',fog:'Distance haze',stars:'Star background'})[k]}</label>)}{(['brightness','contrast'] as const).map(k=><label key={k}>{k} · {appearance[k].toFixed(2)}<input type="range" min={0.4} max={2} step={0.05} value={appearance[k]} onChange={e=>setAppearance(a=>({...a,[k]:Number(e.target.value)}))}/></label>)}</section></>}
 {tab==='Calculators'&&<><label>Calculator<select value={calcId} onChange={e=>setCalcId(e.target.value)}>{[...new Set(CALCULATORS.map(c=>c.category))].map(category=><optgroup key={category} label={category}>{CALCULATORS.filter(c=>c.category===category).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</optgroup>)}</select></label><CalculatorForm key={calcId} tool={selectedTool} view={view}/><p className="tool-note">Geometric and engineering estimates, not surveyed boundaries or operational navigation guidance. <a href="https://www.movable-type.co.uk/scripts/latlong.html" target="_blank" rel="noreferrer">Geodesy formulas</a> · <a href="https://gml.noaa.gov/grad/solcalc/calcdetails.html" target="_blank" rel="noreferrer">Solar approximation</a></p></>}
 </div></aside>;
}
